= Spend a Nested Segwit P2SH-P2WPKH UTXO

____

To follow along this tutorial

* Execute all the transaction code in one go by typing `node code/filename.js`
* Or enter the commands step-by-step by `cd` into `./code` then type `node` in a terminal to open the Node.js REPL
* Open the Bitcoin Core GUI console or use `bitcoin-cli` for the Bitcoin Core commands
* Use `bx` aka `Libbitcoin-explorer` as a handy complement

____

Let's spend a P2SH-P2WPKH output (embedded Segwit) and create a new P2WPKH output.

== Create a UTXO to spend from

Import libraries, test wallets and set the network

[source,javascript]
----
const bitcoin = require('bitcoinjs-lib')
const { alice, bob } = require('./wallets.json')
const network = bitcoin.networks.regtest

----

Send 1 BTC to alice_1 embedded Segwit P2SH-P2WPKH address in order to create a P2SH-P2WPKH UTXO (which is in fact a regular P2SH UTXO).

____

Check out the address in your `wallets.json` file in the `code` directory. Replace the address if necessary.

[source,bash]
----
sendtoaddress 2MzFvFvnhFskGnVQpUr1ZPr4wYWLwf211s6 1
----

____

Inspect the transaction.

[source,bash]
----
getrawtransaction "txid" true
----

Get the output index so that we have the outpoint (txid / vout).

____

Find the output index (or vout) under `details &gt; vout`.

____

You can note that the UTXO is of type `scripthash`, which means that it is a P2SH UTXO.

____

Read more about P2SH here

* https://bitcoin.org/en/developer-guide#p2sh-scripts
* https://en.bitcoin.it/wiki/Pay_to_script_hash
* https://github.com/bitcoin/bips/blob/master/bip-0016.mediawiki

____

== Creating the transaction

Now let's spend the P2SH-P2WPKH UTXO with BitcoinJS.

Create a bitcoinJS key pair object for the spender alice_1. Create a P2WPKH payment address and pass it to the P2SH payment method.

[source,javascript]
----
const keyPairAlice1 = bitcoin.ECPair.fromWIF(alice[1].wif, network)
const p2wpkhAlice1 = bitcoin.payments.p2wpkh({pubkey: keyPairAlice1.publicKey, network})
const p2shAlice1 = bitcoin.payments.p2sh({redeem: p2wpkhAlice1, network})
----

Create a key pair object and a P2PKH address for the recipient bob_1.

[source,javascript]
----
const keyPairBob1 = bitcoin.ECPair.fromWIF(bob[1].wif, network)
const p2wpkhBob1 = bitcoin.payments.p2wpkh({pubkey: keyPairBob1.publicKey, network})
----

Create a BitcoinJS transaction builder object.

[source,javascript]
----
const txb = new bitcoin.TransactionBuilder(network)
----

[source,javascript]
----
txb.addInput('TX_ID', TX_VOUT)
txb.addOutput(p2wpkhBob1.address, 999e5)
----

The redeem script is composed of a `0` version byte and a 20 bytes witness program, HASH160 of alice_1 public key. It is the same as the previous output script `p2wpkhAlice1.output` that we pass to `txb.addInput()` in https://github.com/bitcoin-studio/Bitcoin-Programming-with-BitcoinJS/tree/64d6ce54da567802508ffdc79e00a21060d8450d/part-two-pay-to-public-key-hash/p2sh_p2wpkh/p2wpkh/04_1_p2wpkh_spend_1_1.md[Spend a Native Segwit P2WPKH UTXO].

[source,javascript]
----
// txb.sign(index, keyPair, redeemScript, sign.hashType, value, witnessScript)
txb.sign(0, keyPairAlice1, p2shAlice1.redeem.output, null, 1e8, null)
----

Finally we can build the transaction and get the raw hex serialization.

[source,javascript]
----
const tx = txb.build()
console.log('Transaction hexadecimal:')
console.log(tx.toHex())
----

Inspect the raw transaction with Bitcoin Core CLI, check that everything is correct.

[source,bash]
----
decoderawtransaction "hexstring"
----

== Broadcasting the transaction

It's time to broadcast the transaction.

[source,bash]
----
sendrawtransaction "hexstring"
----

Inspect the transaction.

[source,bash]
----
getrawtransaction "txid" true
----

== Observations

In the vin section the scriptSig is the redeem script. When passed through HASH160 it should match the hash contained in the script of the `scripthash` UTXO that we are spending.

[source,bash]
----
$ bx bitcoin 160 0014fb8820f35effa054399540b8ca86040d8ddaa4d5
4cea7ef76a4423240d5f06d96868726f57bd7d30
----

The signature in `txinwitness` is then verified against alice_1 public key.

In the vout section we have one `witness_v0_keyhash` UTXO.

== What's Next?

Advance through "Part Three: Pay To Script Hash" with https://github.com/bitcoin-studio/Bitcoin-Programming-with-BitcoinJS/tree/64d6ce54da567802508ffdc79e00a21060d8450d/part-two-pay-to-public-key-hash/part-three-pay-to-script-hash/bitcoin_script_puzzles/README.md[Puzzles].