= Data Anchoring with OP_RETURN
:page-codeurl: {codebaseurl}data_anchoring_op_return.js

include::bitcoinjs-guide:ROOT:partial$start-help.adoc[]

Let's store for eternity some data on the Bitcoin blockchain using the special OP_RETURN opcode. It will create a special `nulldata` output type.

An output using an OP_RETURN is provably unspendable, so we don't need to lock any BTC in this UTXO. However, we still need to pay the miner fees, so we will spend BTC from a previous P2WPKH UTXO, create one `nulldata` UTXO and an other one for the change, leaving the difference as mining fees.

For more information about OP_RETURN check out:

* https://bitcoin.org/en/transactions-guide#null-data[Bitcoin Developer Guide - Nulldata Output Type^]
* https://arxiv.org/pdf/1702.01024.pdf[An analysis of Bitcoin OP RETURN metadata^]


== Create a UTXO to spend from

Let's create a P2WPKH UTXO to spend from.

.Import libraries, test wallet and set the network.
[source,javascript]
----
const bitcoin = require('bitcoinjs-lib')
const { alice } = require('./wallets.json')
const network = bitcoin.networks.regtest
----

.Send 1 BTC to alice_1 P2WPKH address via Bitcoin Core CLI.
 sendtoaddress bcrt1qlwyzpu67l7s9gwv4gzuv4psypkxa4fx4ggs05g 1

.Get the output index so that we have the outpoint (txid / vout).
 gettransaction TX_ID

NOTE: Find the output index (or vout) under menu:details[vout].


== Creating the transaction

Now let's create our OP_RETURN P2PKH UTXO.

.Create a bitcoinJS key pair object for the spender alice_1 and a P2WPKH address that we will use for the change.
[source,javascript]
----
const keyPairAlice1 = bitcoin.ECPair.fromWIF(alice[1].wif, network)
----

.Create a PSBT.
[source,javascript]
----
const psbt = new bitcoin.Psbt({network})
----

.Create the input by filling TX_ID and TX_VOUT.
[source,javascript]
----
psbt
  .addInput({
    hash: 'TX_ID',
    index: TX_VOUT,
    witnessUtxo: {
      script: Buffer.from('0014' + alice[1].pubKeyHash, 'hex'),
      value: 1e8,
    },
  })
----

.Create an OP_RETURN output with BitcoinJS `embed` payment method.
[source,javascript]
----
const data = Buffer.from('Programmable money FTW', 'utf8')
const embed = bitcoin.payments.embed({data: [data]})

psbt
  .addOutput({
    script: embed.output,
    value: 0,
  })
----

NOTE: An output using an OP_RETURN is provably unspendable, the script will always evaluate to _false_.
For this reason, and because this is a Bitcoin Core policy rule, the value of an OP_RETURN output is set to 0.

.Create a second output to get back the change. 100 000 000 - 100 000(fees) = 99 900 000 sats
[source,javascript]
----
psbt
  .addOutput({
    address: alice[1].p2wpkh,
    value: 999e5,
  })
----

Keep note of the bitcoin value of the UTXO we are spending, necessary because we are spending a P2WPKH.

.Alice_1 signs the first input.
[source,javascript]
----
psbt.signInput(0, keyPairAlice1)
----

.Finalize the PSBT.
[source,javascript]
----
psbt.validateSignaturesOfInput(0)
psbt.finalizeAllInputs()
----

.Finally we can extract the transaction and get the raw hex serialization.
[source,javascript]
----
console.log('Transaction hexadecimal:')
console.log(psbt.extractTransaction().toHex())
----

.Inspect the raw transaction with Bitcoin Core CLI, check that everything is correct.
[source,bash]
----
decoderawtransaction TX_HEX
----

== Broadcasting the transaction

.It's time to broadcast the transaction.
[source,bash]
----
sendrawtransaction TX_HEX
----

.Inspect the transaction.
[source,bash]
----
getrawtransaction TX_ID true
----


== Observations

We note that the OP_RETURN UTXO is marked with the special type `nulldata`.

To decode the OP_RETURN data we can use the `xxd` library in a terminal which make a hexdump or the reverse.

[source,bash]
----
echo 50726f6772616d6d61626c65206d6f6e65792046545721 | xxd -p -r
----