= Bitcoin Programming with BitcoinJS, Bitcoin Core and LND

Welcome to the non-official _Bitcoin Programming with BitcoinJS_ extensive guide! You will learn how to create various types of Bitcoin transactions using the version 4 of https://github.com/bitcoinjs/bitcoinjs-lib[BitcoinJS^] library.

We will use the Bitcoin Core command-line interface in Regtest mode for various common tasks, as well as some complementary libraries like `bx` aka https://github.com/libbitcoin/libbitcoin-explorer[Libbitcoin Explorer^].

Throughout this guide, we want to provide you with sufficient explanation to each command to understand it without drowning in information. You can refer to additional resources to better understand the Bitcoin protocol. For example, check out our https://www.bitcoin-studio.com/resources[Bitcoin Studio presentations^].

At the moment, Bitcoin Javascript tutorials are still very scarce, but we believe it doesn't have to be this way. The following guide intends to address this problem.

This guide is maintained on https://github.com/bitcoin-studio/Bitcoin-Programming-with-BitcoinJS[GitHub^] and available at
https://bitcoinjs-guide.bitcoin-studio.com


== Requirements

Having prior theoretical knowledge of the Bitcoin protocol will surely help, but we provide comprehensive explanation throughout this guide so it fits for beginners.

Technical requirements

* Node v10 recommended
* BitcoinJS v4
* Bitcoin Core v18
* Bash or a Bash interpreter like Cygwin or Windows Subsystem for Linux (WSL)
* JQ (json parser)
* Libbitcoin Explorer v3 (optional)


== Copyright

Unless otherwise noted, the contents of this repository are Copyright ©2019 by https://www.bitcoin-studio.com[Bitcoin Studio] and are licensed https://github.com/bitcoin-studio/Bitcoin-Programming-with-BitcoinJS/blob/master/LICENSE/README.md[GPL v3].


== Disclaimer

* This guide is not an official documentation
* You must check the BitcoinJS repository for up-to-date code
* Non-standard scripts are exposed for educational purposes
* The author of this guide is not responsible for any loss of funds


== Table of Contents

=== Part One: Preparing The Work Environment

include::../nav.adoc[tag=nav1]

=== Part Two: Pay To Public Key Hash

include::../nav.adoc[tag=nav2]

=== Part Three: Pay To Script Hash

include::../nav.adoc[tag=nav3]

=== Part Four: Data Embedding

include::../nav.adoc[tag=nav4]

=== Tools

include::../nav.adoc[tag=nav5]


Please consider making a donation on my https://tippin.me/@janakaSteph[Tippin.me^] so that I can continue producing free educational
content. ❤️