= Multi-signature Legacy 2 of 4
:page-codeurl: {codebaseurl}multisig_p2sh_2_4.js

include::bitcoinjs-guide:ROOT:partial$start-help.adoc[]

Let's create a 2 of 4 multi-signature with a legacy P2SH transaction.


== Creating and Funding the P2SH

.Import libraries, test wallets and set the network
[source,javascript]
----
const bitcoin = require('bitcoinjs-lib')
const { alice, bob, carol, dave } = require('./wallets.json')
const network = bitcoin.networks.regtest
----

.Prepare four keypairs.
[source,javascript]
----
const keyPairAlice1 = bitcoin.ECPair.fromWIF(alice[1].wif, network)
const keyPairBob1 = bitcoin.ECPair.fromWIF(bob[1].wif, network)
const keyPairCarol1 = bitcoin.ECPair.fromWIF(carol[1].wif, network)
const keyPairDave1 = bitcoin.ECPair.fromWIF(dave[1].wif, network)
----

.And an other alice_2 that will redeem the multi-signature funds.
[source,javascript]
----
const keyPairAlice2 = bitcoin.ECPair.fromWIF(alice[2].wif, network)
const p2wpkhAlice2 = bitcoin.payments.p2wpkh({pubkey: keyPairAlice2.publicKey, network})
----

.Create the locking script with the special `p2ms` payment method.
[source,javascript]
----
const p2ms = bitcoin.payments.p2ms({
  m: 2, pubkeys: [
    keyPairAlice1.publicKey,
    keyPairBob1.publicKey,
    keyPairCarol1.publicKey,
    keyPairDave1.publicKey], network})

console.log('Script:')
console.log(p2ms.output.toString('hex'))
----

.Check the locking script.
[source,bash]
----
decodescript SCRIPT
----

....
02 03745c9aceb84dcdeddf2c3cdc1edb0b0b5af2f9bf85612d73fa6394758eaee35d 027efbabf425077cdbceb73f6681c7ebe2ade74a65ea57ebcf0c42364d3822c590
023a11cfcedb993ff2e7523f92e359c4454072a66d42e8b74b4b27a8a1258abddd 02e9d617f38f8c3ab9a6bde36ce991bafb295d7adba457699f8620c8160ec9e87a 04
OP_CHECKMULTISIG
....

Feed the `p2sh` method with the special BitcoinJS `p2ms` object. The `p2sh` method generates an object that contains the P2SH address.

[source,javascript]
----
const p2sh = bitcoin.payments.p2sh({redeem: p2ms, network})
console.log('P2SH address')
console.log(p2sh.address)
----

.Send 1 BTC to this P2SH address.
[source,bash]
----
sendtoaddress 2NAjnUkVxAv34bnfpC1edhW5qstF2QHSUk5 1
----

.Get the output index so that we have the outpoint (txid / vout).
[source,bash]
----
gettransaction TX_ID
----

TIP: Find the output index (or vout) under menu:details[vout].


== Preparing the spending transaction

Now let's prepare the spending transaction by setting input and output and having two people (private keys) to sign the transaction. Here alice_1 ad bob_1 will redeem the P2SH multi-signature and send the funds to alice_2 P2WPKH address.

.Create a BitcoinJS transaction builder object.
[source,javascript]
----
const txb = new bitcoin.TransactionBuilder(network)
----

.Create the input by referencing the outpoint of our P2SH funding transaction.
[source,javascript]
----
txb.addInput('TX_ID', TX_VOUT)
----

.Create the output that will send the funds to alice_2 P2WPKH address, leaving 100 000 satoshis as mining fees.
[source,javascript]
----
txb.addOutput(p2wpkhAlice2.address, 999e5)
----

.Alice_1 and bob_1 now sign the transaction.
[source,javascript]
----
// txb.sign(index, keyPair, redeemScript, sign.hashType, value, witnessScript)
txb.sign(0, keyPairAlice1, p2sh.redeem.output)
txb.sign(0, keyPairBob1, p2sh.redeem.output)
----

NOTE: Note that we need to provide the redeemScript as third parameter of the `sign` method.

.Build the transaction and get the raw hex serialization.
[source,javascript]
----
const tx = txb.build()
console.log('Transaction hexadecimal:')
console.log(tx.toHex())
----

.Inspect the raw transaction with Bitcoin Core CLI, check that everything is correct.
[source,bash]
----
decoderawtransaction TX_HEX
----


== Broadcasting the transaction

.It's time to broadcast the transaction via Bitcoin Core CLI.
[source,bash]
----
sendrawtransaction TX_HEX
----

.Inspect the transaction.
[source,bash]
----
getrawtransaction TX_ID true
----


== Observations

We can see that the unlocking script contains

* a useless dummy but mandatory `00` value due to a bug in `OP_CHECKMULTISIG`
* Alice_1 and bob_1 signatures
* and our redeem script