= Multi-signatures

To learn more

* https://github.com/bitcoin/bips/blob/master/bip-0011.mediawiki[BIP11 - M-of-N Standard Transactions]
* https://en.bitcoinwiki.org/wiki/Multisignature[bitcoinwiki.org - Multisignature]
* P2P trading exchange based on Bitcoin multi-signature https://hodlhodl.com/[hodlhodl.com]

Multi-signature (multisig) refers to requiring more than one key to authorize a Bitcoin transaction. It is generally used to divide up responsibility for possession of bitcoins.

Standard transactions on the Bitcoin network could be called "single-signature transactions" because transfers require only one signature — from the owner of the private key associated with the Bitcoin address. However, the Bitcoin network supports much more complicated transactions that require the signatures of multiple people before the funds can be transferred. These are often referred to as M-of-N transactions.

The idea is that bitcoins become "encumbered" by providing addresses of multiple parties, thus requiring cooperation of those parties in order to do anything with them. These parties can be people, institutions or programmed scripts.